# Generated by Django 5.1.6 on 2025-02-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregrado',
            fields=[
                ('cod_pregrado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('creditos', models.IntegerField()),
                ('nota_minima', models.IntegerField()),
            ],
            options={
                'db_table': 'pregrado',
                'managed': False,
            },
        ),
    ]
