# Generated by Django 5.1.6 on 2025-02-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('cod_sede', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sede',
                'managed': False,
            },
        ),
    ]
